# Generated by Django 5.2.5 on 2025-08-15 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apichat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicDebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='debatesession',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='apichat.topicdebate'),
        ),
    ]
