# Generated by Django 5.2.5 on 2025-10-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apichat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicDebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='debatesession',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
