# Generated by Django 5.2.5 on 2025-09-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apichat', '0002_topicdebate_alter_debatesession_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debatesession',
            name='topic',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='TopicDebate',
        ),
    ]
